#!/bin/bash

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap           10
bspc config top_padding          75  # window_gap under panel
bspc config bottom_padding       25  # (35 - window_gap)
bspc config left_padding         25
bspc config right_padding        25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle  false

bspc rule -a Emacs locked=on
bspc rule -a URxvt:scratchpad sticky=on state=floating hidden=on locked=on
bspc rule -a Zathura state=tiled

wal -i ${HOME}/.local/share/img/ -o ${HOME}/.local/bin/wal-set
${HOME}/.local/bin/lemonbar-run &
