#!/bin/bash

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap           10
bspc config top_padding          25  # (35 - window_gap)
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Emacs locked=on state=tiled
bspc rule -a URxvt:scratchpad sticky=on state=floating hidden=on locked=on

source ${HOME}/.cache/wal/colors.sh

# Set the border colors.
bspc config presel_feedback_color "$color1"

# Send event stream to status bar
bspc subscribe report > "$PANEL_FIFO" &
