#!/bin/bash

export SXHKD_SHELL='/bin/sh'
sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap           35

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

${HOME}/.local/bin/new-wal

source $HOME/.cache/wal/colors.sh &

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc rule -a Emacs state=tiled follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton --config $HOME/.config/compton/compton.conf -b
polybar bottom &
